#!/usr/bin/env python3
#
# Generates fuzzing/fuzz_h2p_seed_corpus/ for fuzz_http_h2p.
#
# Requires the Python "h2" package: pip install --user h2
#
# fuzz_http_h2p's own harness (fuzzing/nxt_http_h2p_fuzz.c) always
# prepends the fixed 24-byte client connection preface before feeding a
# corpus file to nghttp2, exactly the way nxt_h2p_conn_init() expects it on
# the wire.  h2.connection.H2Connection.initiate_connection() writes that
# same preface into its own output, so every generator below strips it
# (see strip_preface()) before saving -- a seed file holds everything
# *after* the preface: the client's initial SETTINGS frame onward.
#
# Some seeds are built with the h2 library, which refuses to emit
# protocol violations; a handful of others below build raw frames by hand
# (raw_frame()) specifically to cover the malformed cases h2 will not
# produce: a bad pseudo-header path, a header list that blows past the
# server's advertised limit, and non-HPACK garbage.
#
# fuzz_h2p_seed_corpus/regress_stream_out_leak_on_conn_expire.bin is not
# generated by this script: it is a libFuzzer -minimize_crash artifact
# (a HEADERS(END_STREAM|END_HEADERS) request immediately followed by a
# client GOAWAY) that reproduces a real nxt_h2proto.c leak -- see the
# fuzzing session notes / PR description for the root cause -- and is
# committed as-is so the regression stays covered once fixed.

import os
import struct

import h2.connection
import h2.config

OUT_DIR = os.path.join(os.path.dirname(__file__), "fuzz_h2p_seed_corpus")

PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"


def strip_preface(data):
    assert data.startswith(PREFACE), "h2 did not emit the preface first"
    return data[len(PREFACE):]


def client():
    config = h2.config.H2Configuration(client_side=True)
    conn = h2.connection.H2Connection(config=config)
    conn.initiate_connection()
    return conn


def save(name, data):
    path = os.path.join(OUT_DIR, name)
    with open(path, "wb") as f:
        f.write(data)
    print("wrote %s (%d bytes)" % (path, len(data)))


def raw_frame(frame_type, flags, stream_id, payload):
    length = len(payload)
    return struct.pack(">I", length)[1:] + bytes([frame_type, flags]) \
        + struct.pack(">I", stream_id) + payload


# --- valid, ordinary requests -----------------------------------------

def gen_get():
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
        ("user-agent", "fuzz-h2p/1.0"),
    ], end_stream=True)
    save("get.bin", strip_preface(conn.data_to_send()))


def gen_get_query_and_cookies():
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/search?q=fuzz&lang=en"),
        ("cookie", "a=1; b=2"),
        ("accept", "*/*"),
    ], end_stream=True)
    save("get_query_cookies.bin", strip_preface(conn.data_to_send()))


def gen_post_body():
    conn = client()
    conn.send_headers(1, [
        (":method", "POST"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/upload"),
        ("content-type", "application/octet-stream"),
        ("content-length", "13"),
    ])
    conn.send_data(1, b"hello, world!", end_stream=True)
    save("post_body.bin", strip_preface(conn.data_to_send()))


def gen_post_body_no_content_length():
    # No content-length: nxt_h2p_request_headers_done() takes the chunked
    # (unknown length) body_alloc() path.
    conn = client()
    conn.send_headers(1, [
        (":method", "POST"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/upload"),
    ])
    conn.send_data(1, b"a" * 256, end_stream=True)
    save("post_body_no_len.bin", strip_preface(conn.data_to_send()))


def gen_post_body_split_frames():
    # Same body, several DATA frames -- exercises the accounting in
    # nxt_h2p_on_data_chunk_recv() across more than one chunk.
    conn = client()
    conn.send_headers(1, [
        (":method", "POST"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/upload"),
        ("content-length", "3000"),
    ])
    for _ in range(30):
        conn.send_data(1, b"x" * 100)
    conn.send_data(1, b"", end_stream=True)
    save("post_body_split.bin", strip_preface(conn.data_to_send()))


def gen_post_body_over_declared():
    # DATA adds up to more than the declared content-length; nghttp2 itself
    # is expected to catch this, but nxt_h2p_on_data_chunk_recv() has its
    # own belt-and-braces check (len > nxt_buf_mem_free_size()).
    conn = client()
    conn.send_headers(1, [
        (":method", "POST"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/upload"),
        ("content-length", "4"),
    ])
    data = strip_preface(conn.data_to_send())
    # Hand-append a DATA frame with more bytes than declared; h2 would
    # refuse to build this itself.
    data += raw_frame(0x0, 0x1, 1, b"way too much data for four bytes")
    save("post_body_over_declared.bin", data)


def gen_put_trailers():
    conn = client()
    conn.send_headers(1, [
        (":method", "PUT"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/x"),
        ("content-length", "5"),
    ])
    conn.send_data(1, b"hello")
    # Trailers: an extra HEADERS frame (HCAT_HEADERS), not HCAT_REQUEST;
    # nxt_h2p_request_end_stream() runs, the fields themselves are dropped.
    conn.send_headers(1, [("x-trailer", "done")], end_stream=True)
    save("put_trailers.bin", strip_preface(conn.data_to_send()))


def gen_options_star():
    # ":path" is "*", only legal for OPTIONS (RFC 9113, 8.3.1).
    conn = client()
    conn.send_headers(1, [
        (":method", "OPTIONS"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "*"),
    ], end_stream=True)
    save("options_star.bin", strip_preface(conn.data_to_send()))


def gen_dot_segment_path():
    # Exercises nxt_http_parse_complex_target()'s dot-segment normalization
    # by way of nxt_h2p_request_target().
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/a/../../b/./c%2e%2e/d"),
    ], end_stream=True)
    save("dot_segment_path.bin", strip_preface(conn.data_to_send()))


def gen_host_matches_authority():
    # A "host" field that agrees with ":authority": the fast-path compare
    # in nxt_h2p_on_header() (RFC 9113 8.3.1), not the mismatch error.
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
        ("host", "example.com"),
    ], end_stream=True)
    save("host_matches_authority.bin", strip_preface(conn.data_to_send()))


def gen_host_mismatch():
    # "host" disagreeing with ":authority" (RFC 9113, 8.3.1) is a request
    # nxt_h2p_on_header() rejects (NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE);
    # the h2 library validates this itself before send_headers() ever
    # builds a frame, so this goes through hpack directly, like the other
    # protocol violations below.
    import hpack

    encoder = hpack.Encoder()
    block = encoder.encode([
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
        ("host", "evil.example"),
    ])
    conn = client()
    preface = strip_preface(conn.data_to_send())
    frame = raw_frame(0x1, 0x5, 1, block)
    save("host_mismatch.bin", preface + frame)


def gen_connect_no_path():
    # CONNECT has no ":path"; nxt_h2p_request_headers_done() answers 405,
    # not 400, for exactly this method.
    conn = client()
    conn.send_headers(1, [
        (":method", "CONNECT"),
        (":authority", "example.com:443"),
    ], end_stream=True)
    save("connect_no_path.bin", strip_preface(conn.data_to_send()))


# --- frame-type / lifecycle coverage -----------------------------------

def gen_priority_only():
    conn = client()
    conn.prioritize(1, weight=42)
    save("priority_only.bin", strip_preface(conn.data_to_send()))


def gen_priority_then_request():
    conn = client()
    conn.prioritize(3, weight=10)
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ], end_stream=True)
    save("priority_then_request.bin", strip_preface(conn.data_to_send()))


def gen_rst_after_headers():
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ])
    conn.reset_stream(1, error_code=8)  # CANCEL
    save("rst_after_headers.bin", strip_preface(conn.data_to_send()))


def gen_rst_before_headers_done():
    # RST_STREAM while the header block itself is mid-flight is not
    # something the h2 library will construct (it tracks stream state),
    # so build it by hand: HEADERS without END_HEADERS, then RST_STREAM.
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ], end_stream=True)
    data = strip_preface(conn.data_to_send())
    data += raw_frame(0x3, 0x0, 1, struct.pack(">I", 0x8))
    save("rst_before_headers_done.bin", data)


def gen_settings_flood():
    conn = client()
    data = strip_preface(conn.data_to_send())
    # NXT_H2P_MAX_SETTINGS is 32; well past that, well under
    # NGHTTP2_ERR_TOO_MANY_SETTINGS's own bookkeeping cost.
    one = raw_frame(0x4, 0x0, 0, struct.pack(">HI", 4, 100))
    save("settings_flood.bin", data + one * 64)


def gen_ping():
    conn = client()
    conn.ping(b"01234567")
    save("ping.bin", strip_preface(conn.data_to_send()))


def gen_window_update():
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ], end_stream=True)
    conn.increment_flow_control_window(1024)
    save("window_update.bin", strip_preface(conn.data_to_send()))


def gen_padding():
    conn = client()
    conn.send_headers(1, [
        (":method", "POST"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
        ("content-length", "4"),
    ])
    conn.send_data(1, b"ping", end_stream=True, pad_length=16)
    save("padding.bin", strip_preface(conn.data_to_send()))


def gen_multiple_streams():
    conn = client()
    for sid in (1, 3, 5, 7):
        conn.send_headers(sid, [
            (":method", "GET"),
            (":scheme", "https"),
            (":authority", "example.com"),
            (":path", "/%d" % sid),
        ], end_stream=True)
    save("multiple_streams.bin", strip_preface(conn.data_to_send()))


def gen_continuation():
    # A header value long enough that h2 must split the HEADERS block
    # across CONTINUATION frames (NXT_H2P_MAX_CONTINUATIONS is 8).
    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
        ("x-pad-1", "v" * 4000),
        ("x-pad-2", "w" * 4000),
        ("x-pad-3", "y" * 4000),
    ], end_stream=True)
    save("continuation.bin", strip_preface(conn.data_to_send()))


def gen_many_small_fields():
    conn = client()
    headers = [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ]
    headers += [("x-field-%02d" % i, "v") for i in range(40)]
    conn.send_headers(1, headers, end_stream=True)
    save("many_small_fields.bin", strip_preface(conn.data_to_send()))


# --- malformed / hostile input, built by hand ---------------------------

def gen_bad_path_no_slash():
    # ":path" that is neither "/..." nor the OPTIONS-only "*":
    # nxt_h2p_request_target() answers 400.  h2 will not build a request
    # with this ":path" itself (it validates pseudo-headers), so the HEADERS
    # frame is HPACK-encoded here directly via hyperframe/hpack primitives
    # that h2 itself uses, bypassing only its request-line validation.
    import hpack

    encoder = hpack.Encoder()
    block = encoder.encode([
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "not-a-path"),
    ])
    conn = client()
    preface = strip_preface(conn.data_to_send())
    frame = raw_frame(0x1, 0x5, 1, block)  # END_STREAM | END_HEADERS
    save("bad_path_no_slash.bin", preface + frame)


def gen_huge_header_field_name():
    # A field name over NXT_H2P_MAX_FIELD_NAME (255, nxt_http_field_t's
    # name_length is a uint8_t): the block is still consumed so HPACK state
    # stays in sync, but nxt_h2p_on_header() answers
    # NXT_HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE instead of storing it.
    import hpack

    encoder = hpack.Encoder()
    block = encoder.encode([
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
        ("x-" + "n" * 300, "v"),
    ])
    conn = client()
    preface = strip_preface(conn.data_to_send())
    frame = raw_frame(0x1, 0x5, 1, block)
    save("huge_header_field_name.bin", preface + frame)


def gen_header_list_too_large():
    # Enough fields, each within limits individually, to push
    # stream->header_list_size past large_header_buffer_size *
    # large_header_buffers -- the other branch of the same check.
    conn = client()
    headers = [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ]
    headers += [("x-bulk-%03d" % i, "v" * 200) for i in range(200)]
    conn.send_headers(1, headers, end_stream=True)
    save("header_list_too_large.bin", strip_preface(conn.data_to_send()))


def gen_garbage_after_valid_settings():
    # A well-formed SETTINGS frame followed by bytes that are not a valid
    # frame at all -- nghttp2_session_mem_recv() should fail the session
    # (NGHTTP2_ERR_*), driving nxt_h2p_conn_abort()'s error-code switch.
    conn = client()
    data = strip_preface(conn.data_to_send())
    save("garbage_after_settings.bin", data + b"\xff" * 32)


def gen_oversize_frame_header_only():
    # A frame header claiming a length far past SETTINGS_MAX_FRAME_SIZE
    # with no payload following: nghttp2 must reject this on the header
    # alone (a length lie), not read past the buffer.
    frame = struct.pack(">I", 0x00FFFFFF)[1:] + bytes([0x0, 0x0]) \
        + struct.pack(">I", 0)
    save("oversize_frame_header_only.bin", frame)


def gen_stream_id_zero_headers():
    # HEADERS on stream 0 is a connection error the h2 library also
    # refuses to build; hand-crafted like the other protocol violations.
    import hpack

    encoder = hpack.Encoder()
    block = encoder.encode([
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ])
    conn = client()
    preface = strip_preface(conn.data_to_send())
    frame = raw_frame(0x1, 0x5, 0, block)
    save("stream_id_zero_headers.bin", preface + frame)


def gen_even_stream_id():
    # Client-initiated streams must be odd; stream 2 is a protocol error.
    import hpack

    encoder = hpack.Encoder()
    block = encoder.encode([
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/"),
    ])
    conn = client()
    preface = strip_preface(conn.data_to_send())
    frame = raw_frame(0x1, 0x5, 2, block)
    save("even_stream_id.bin", preface + frame)


def gen_data_before_headers():
    # DATA for a stream that never got a HEADERS: nghttp2 answers this
    # itself, but it drives nxt_h2p_on_data_chunk_recv() with stream ==
    # NULL, which is exactly the branch that must not touch stream->r.
    frame = raw_frame(0x0, 0x1, 1, b"orphan data")
    save("data_before_headers.bin", frame)


def gen_two_requests_second_bad_path():
    # A good request followed by one with a bad ":path" on the next
    # stream -- checks that per-stream error handling for one stream does
    # not disturb another already in flight on the same connection.
    import hpack

    conn = client()
    conn.send_headers(1, [
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "/ok"),
    ], end_stream=True)
    data = strip_preface(conn.data_to_send())

    encoder = hpack.Encoder()
    block = encoder.encode([
        (":method", "GET"),
        (":scheme", "https"),
        (":authority", "example.com"),
        (":path", "nope"),
    ])
    data += raw_frame(0x1, 0x5, 3, block)
    save("two_requests_second_bad_path.bin", data)


GENERATORS = [
    gen_get,
    gen_get_query_and_cookies,
    gen_post_body,
    gen_post_body_no_content_length,
    gen_post_body_split_frames,
    gen_post_body_over_declared,
    gen_put_trailers,
    gen_options_star,
    gen_dot_segment_path,
    gen_host_matches_authority,
    gen_host_mismatch,
    gen_connect_no_path,
    gen_priority_only,
    gen_priority_then_request,
    gen_rst_after_headers,
    gen_rst_before_headers_done,
    gen_settings_flood,
    gen_ping,
    gen_window_update,
    gen_padding,
    gen_multiple_streams,
    gen_continuation,
    gen_many_small_fields,
    gen_bad_path_no_slash,
    gen_huge_header_field_name,
    gen_header_list_too_large,
    gen_garbage_after_valid_settings,
    gen_oversize_frame_header_only,
    gen_stream_id_zero_headers,
    gen_even_stream_id,
    gen_data_before_headers,
    gen_two_requests_second_bad_path,
]


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    for gen in GENERATORS:
        gen()

    print("%d seed files in %s" % (len(GENERATORS), OUT_DIR))


if __name__ == "__main__":
    main()
